--BÀI TẬP 1
SELECT NAME FROM CITY
WHERE POPULATION >120000
 AND COUNTRYCODE ='USA'
-- BÀI TẬP 2
SELECT*FROM CITY
WHERE COUNTRYCODE='JPN'
-- BÀI TẬP 3
SELECT CITY, STATE
FROM STATION
-- BÀI TẬP 4
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE 'A%' OR CITY LIKE 'E%' OR CITY LIKE 'I%' OR CITY LIKE 'O%' OR CITY LIKE 'U%'
-- BÀI TẬP 5
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE '%A' OR CITY LIKE '%E' OR CITY LIKE '%I' OR CITY LIKE '%O' OR CITY LIKE '%U'
-- BÀI TẬP 6
SELECT DISTINCT CITY FROM STATION
WHERE CITY NOT LIKE 'A%' AND CITY NOT LIKE 'E%' AND CITY NOT LIKE 'I%' AND CITY NOT LIKE 'O%' AND CITY NOT LIKE 'U%'
-- BÀI TẬP 7
SELECT NAME FROM EMPLOYEE
ORDER BY NAME
-- BÀI TẬP 8
SELECT NAME FROM EMPLOYEE
WHERE SALARY >2000
AND MONTHS <10
ORDER BY EMPLOYEE_ID ASC
-- BÀI TẬP 9
SELECT PRODUCT_ID FROM PRODUCTS
WHERE LOW_FATS ='Y'
AND RECYCLABLE='Y'
-- BÀI TẬP 10 ???
SELECT NAME
FROM CUSTOMER
WHERE REFEREE_ID <> 2 OR REFEREE_ID IS NULL
-- BÀI TẬP 11
SELECT NAME, POPULATION, AREA FROM WORLD
WHERE AREA >= 3000000
OR POPULATION >=25000000
-- BÀI TẬP 12
SELECT DISTINCT AUTHOR_ID AS ID FROM VIEWS
WHERE AUTHOR_ID=VIEWER_ID
ORDER BY AUTHOR_ID ASC
-- BÀI TẬP 13
SELECT PART, assembly_step FROM parts_assembly
WHERE FINISH_DATE IS NULL
-- BÀI TẬP 14
select * from lyft_drivers
WHERE YEARLY_SALARY <=30000 OR YEARLY_SALARY >=70000
-- BÀI TẬP 15
select * from uber_advertising
WHERE YEAR =2019 AND MONEY_SPENT >100000
