-- BÀI 1
SELECT COUNT(DISTINCT COMPANY_ID) AS DUPLICATE
FROM (SELECT COMPANY_ID, TITLE, DESCRIPTION, COUNT(JOB_ID) AS JOB_COUNT
FROM JOB_LISTINGS
GROUP BY COMPANY_ID, TITLE, DESCRIPTION) AS JOB_COUNT_HEHE
WHERE JOB_COUNT>1
-- BÀI 2 (giá trị thì ghi đúng chính tả, đúng định dạng viết hoa, viết thường giùm)
WITH CTE1 AS (
    SELECT CATEGORY, PRODUCT, 
        SUM(SPEND) AS TOTAL_SPEND
    FROM 
        PRODUCT_SPEND
    WHERE 
        EXTRACT(YEAR FROM TRANSACTION_DATE) = 2022
        AND CATEGORY = 'appliance'
    GROUP BY CATEGORY, PRODUCT
    ORDER BY TOTAL_SPEND DESC
    LIMIT 2
), 
CTE2 AS (
    SELECT CATEGORY, PRODUCT, 
        SUM(SPEND) AS TOTAL_SPEND
    FROM PRODUCT_SPEND
    WHERE 
        EXTRACT(YEAR FROM TRANSACTION_DATE) = 2022
        AND CATEGORY = 'electronics'
    GROUP BY CATEGORY, PRODUCT
    ORDER BY TOTAL_SPEND DESC
    LIMIT 2
)

SELECT * FROM CTE1
UNION ALL
SELECT * FROM CTE2;
-- BÀI 3
SELECT COUNT(DISTINCT POLICY_HOLDER_ID) AS policy_holder_count
FROM CALLERS
WHERE POLICY_HOLDER_ID IN (
    SELECT POLICY_HOLDER_ID
    FROM CALLERS
    GROUP BY POLICY_HOLDER_ID
    HAVING COUNT(POLICY_HOLDER_ID) >= 3
);
-- BÀI 4 (BÀI NÀY GIẢI RỒI)
SELECT PAGES.PAGE_ID
FROM PAGES
LEFT JOIN PAGE_LIKES
ON PAGES.PAGE_ID=PAGE_LIKES.PAGE_ID
WHERE PAGE_LIKES.PAGE_ID IS NULL
-- BÀI 5 
WITH CTE1 AS (
    SELECT DISTINCT USER_ID
    FROM USER_ACTIONS
    WHERE EXTRACT(MONTH FROM EVENT_DATE) < 7
), 
CTE2 AS (
    SELECT DISTINCT USER_ID
    FROM USER_ACTIONS
    WHERE EXTRACT(MONTH FROM EVENT_DATE) = 7
)
SELECT 7 AS mth, 
    COUNT(DISTINCT CTE1.USER_ID) AS monthly_active_users
FROM CTE1
JOIN CTE2 ON CTE1.USER_ID = CTE2.USER_ID;
-- BÀI 6
SELECT 
    DATE_FORMAT(trans_date, '%Y-%m') AS month
    , country
    , COUNT(*) AS trans_count
    , SUM(IF(state = 'approved', 1, 0)) AS approved_count
    , SUM(amount) AS trans_total_amount
    , SUM(IF(state = 'approved', amount, 0)) AS approved_total_amount
FROM Transactions
GROUP BY month, country
-- BÀI 7

